CREATE TABLE ds_approval_type_definition (
    id                              VARCHAR(36) NOT NULL,
    tenant_id                       VARCHAR(128) NOT NULL,
    type_key                        VARCHAR(128) NOT NULL,
    handler_key                     VARCHAR(64) NOT NULL,
    name_i18n_json                  JSON NOT NULL,
    description_i18n_json           JSON NOT NULL,
    generator_key                   VARCHAR(128) NOT NULL,
    allowed_operation_kinds_json    JSON NOT NULL,
    generation_rule_json            JSON NOT NULL,
    pending_definition_json         JSON NULL,
    applicable_connections_json     JSON NULL,
    risk_policy_json                JSON NOT NULL,
    status                          VARCHAR(32) NOT NULL,
    definition_revision             BIGINT NOT NULL DEFAULT 0,
    checksum                        CHAR(64) NOT NULL,
    pending_revision                BIGINT NULL,
    pending_checksum                CHAR(64) NULL,
    created_by                      VARCHAR(128) NOT NULL,
    updated_by                      VARCHAR(128) NOT NULL,
    enabled_by                      VARCHAR(128) NULL,
    created_at                      DATETIME(6) NOT NULL,
    updated_at                      DATETIME(6) NOT NULL,
    enabled_at                      DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_approval_type_key (tenant_id, type_key),
    KEY idx_approval_type_catalog (tenant_id, handler_key, status, updated_at)
);

CREATE TABLE ds_approval_request (
    id                              VARCHAR(36) NOT NULL,
    tenant_id                       VARCHAR(128) NOT NULL,
    request_no                      VARCHAR(64) NOT NULL,
    type                            VARCHAR(64) NOT NULL,
    work_order_type_key             VARCHAR(128) NOT NULL,
    work_order_type_revision        BIGINT NOT NULL,
    type_definition_checksum        CHAR(64) NOT NULL,
    title                           VARCHAR(255) NOT NULL,
    summary                         TEXT NULL,
    applicant_user_id               VARCHAR(128) NOT NULL,
    applicant_display_name          VARCHAR(255) NULL,
    source_session_id               VARCHAR(64) NULL,
    source_run_id                   VARCHAR(64) NULL,
    connection_id                   VARCHAR(64) NOT NULL,
    connection_name                 VARCHAR(255) NOT NULL,
    status                          VARCHAR(32) NOT NULL,
    approval_provider               VARCHAR(64) NOT NULL DEFAULT 'builtin',
    external_request_id             VARCHAR(255) NULL,
    content_json                    JSON NOT NULL,
    content_version                 BIGINT NOT NULL DEFAULT 1,
    content_digest                  CHAR(64) NOT NULL,
    execution_mode                  VARCHAR(32) NOT NULL,
    execution_attempt               INT NOT NULL DEFAULT 0,
    latest_execution_status         VARCHAR(32) NULL,
    reviewer_user_id                VARCHAR(128) NULL,
    reviewer_display_name           VARCHAR(255) NULL,
    review_comment                  TEXT NULL,
    execution_owner                 VARCHAR(128) NULL,
    execution_lease_until           DATETIME(6) NULL,
    idempotency_key                 VARCHAR(128) NULL,
    revision                        BIGINT NOT NULL DEFAULT 0,
    created_at                      DATETIME(6) NOT NULL,
    submitted_at                    DATETIME(6) NULL,
    approved_at                     DATETIME(6) NULL,
    rejected_at                     DATETIME(6) NULL,
    finished_at                     DATETIME(6) NULL,
    updated_at                      DATETIME(6) NOT NULL,
    deleted_at                      DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_approval_request_no (tenant_id, request_no),
    UNIQUE KEY uk_approval_request_idempotency (tenant_id, applicant_user_id, idempotency_key),
    KEY idx_approval_request_mine (tenant_id, applicant_user_id, status, updated_at),
    KEY idx_approval_request_review (tenant_id, status, submitted_at),
    KEY idx_approval_request_connection (tenant_id, connection_id, updated_at),
    KEY idx_approval_request_lease (tenant_id, status, execution_lease_until)
);

CREATE TABLE ds_approval_item (
    id                              VARCHAR(36) NOT NULL,
    tenant_id                       VARCHAR(128) NOT NULL,
    request_id                      VARCHAR(36) NOT NULL,
    ordinal                         INT NOT NULL,
    operation_kind                  VARCHAR(64) NOT NULL,
    sql_text                        MEDIUMTEXT NOT NULL,
    normalized_sql_digest           CHAR(64) NOT NULL,
    object_refs_json                JSON NOT NULL,
    risk_level                      VARCHAR(16) NOT NULL,
    warnings_json                   JSON NOT NULL,
    idempotency_strategy            VARCHAR(32) NOT NULL,
    precondition_json               JSON NULL,
    created_at                      DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_approval_item_ordinal (tenant_id, request_id, ordinal),
    KEY idx_approval_item_request (tenant_id, request_id, ordinal)
);

CREATE TABLE ds_approval_resource_claim (
    id                              VARCHAR(36) NOT NULL,
    tenant_id                       VARCHAR(128) NOT NULL,
    request_id                      VARCHAR(36) NOT NULL,
    resource_key                    VARCHAR(512) NOT NULL,
    claim_kind                      VARCHAR(64) NOT NULL,
    active_key                      VARCHAR(16) NULL,
    created_at                      DATETIME(6) NOT NULL,
    released_at                     DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_approval_active_claim (tenant_id, resource_key, active_key),
    KEY idx_approval_claim_request (tenant_id, request_id, active_key)
);

CREATE TABLE ds_approval_execution (
    id                              VARCHAR(36) NOT NULL,
    tenant_id                       VARCHAR(128) NOT NULL,
    request_id                      VARCHAR(36) NOT NULL,
    item_id                         VARCHAR(36) NOT NULL,
    attempt_no                      INT NOT NULL,
    ordinal                         INT NOT NULL,
    status                          VARCHAR(32) NOT NULL,
    query_id                        VARCHAR(128) NOT NULL,
    started_at                      DATETIME(6) NULL,
    finished_at                     DATETIME(6) NULL,
    duration_ms                     BIGINT NULL,
    error_code                      VARCHAR(128) NULL,
    safe_message                    TEXT NULL,
    created_at                      DATETIME(6) NOT NULL,
    updated_at                      DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_approval_execution_item (tenant_id, request_id, attempt_no, item_id),
    UNIQUE KEY uk_approval_execution_query (tenant_id, query_id),
    KEY idx_approval_execution_request (tenant_id, request_id, attempt_no, ordinal)
);

CREATE TABLE ds_approval_node_execution (
    id                              VARCHAR(36) NOT NULL,
    tenant_id                       VARCHAR(128) NOT NULL,
    execution_id                    VARCHAR(36) NOT NULL,
    node_key                        VARCHAR(255) NOT NULL,
    host                            VARCHAR(255) NOT NULL,
    port                            INT NULL,
    status                          VARCHAR(32) NOT NULL,
    duration_ms                     BIGINT NULL,
    error_code                      VARCHAR(128) NULL,
    safe_message                    TEXT NULL,
    raw_log_ref                     VARCHAR(512) NULL,
    started_at                      DATETIME(6) NULL,
    finished_at                     DATETIME(6) NULL,
    created_at                      DATETIME(6) NOT NULL,
    updated_at                      DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_approval_node_execution (tenant_id, execution_id, node_key),
    KEY idx_approval_node_status (tenant_id, execution_id, status)
);

CREATE TABLE ds_approval_event (
    id                              VARCHAR(36) NOT NULL,
    tenant_id                       VARCHAR(128) NOT NULL,
    request_id                      VARCHAR(36) NOT NULL,
    event_type                      VARCHAR(64) NOT NULL,
    actor_user_id                   VARCHAR(128) NOT NULL,
    actor_display_name              VARCHAR(255) NULL,
    safe_message                    TEXT NULL,
    details_json                    JSON NULL,
    external_event_id               VARCHAR(255) NULL,
    created_at                      DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_approval_external_event (tenant_id, event_type, external_event_id),
    KEY idx_approval_event_timeline (tenant_id, request_id, created_at, id)
);
